[book]
authors = ["nikki9750"]
language = "ja"
multilingual = false
src = "src"
title = "Notepad.md"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[preprocessor.pagetoc]
[preprocessor.alerts]
