[book]
authors = ["nikki9750"]
language = "ja"
multilingual = false
src = "src"
title = "Notepad.md"

  [output.html]
  additional-css = ["plugins/mdBook-pagetoc/theme/pagetoc.css"]
  additional-js = ["plugins/mdBook-pagetoc/theme/pagetoc.js"]